# Generated by Django 4.2.5 on 2023-10-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='img',
            field=models.ImageField(blank=True, upload_to='orders/'),
        ),
    ]
