# Generated by Django 4.2.5 on 2023-10-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='img',
        ),
    ]
